url: "http://cebollasrey.com" # the base hostname & protocol for your site, e.g. http://example.com
defaults:
  -
    scope:
      path: ""
    values:
      title: "AgroLopezRuiz S.L."

collections:
  products:
    output: false
